import {
  World,
  Model,
  Reflector,
  Setup,
  SpotLight,
  Torus,
  LingoEditor
} from "."

function App() {
  return (
    <World>
      <LingoEditor />
      <Torus
        uuid="G-rPKBBI1ranoz1IJx8gy"
        x={3.42}
        y={54.97}
        z={170.77}
        scaleX={4}
        scaleY={4}
        scaleZ={4}
        castShadow={false}
        receiveShadow={false}
        emissive
        thickness={0.01}
      />
      <Torus
        uuid="jSncOL3TobowEK4pJ8xv5"
        x={3.42}
        y={54.97}
        z={334.76}
        scaleX={4}
        scaleY={4}
        scaleZ={4}
        castShadow={false}
        receiveShadow={false}
        emissive
        thickness={0.01}
      />
      <Torus
        uuid="SGzujGGEQmU58M8Abg-Zk"
        x={3.42}
        y={54.97}
        z={7.9}
        scaleX={4}
        scaleY={4}
        scaleZ={4}
        castShadow={false}
        receiveShadow={false}
        emissive
        thickness={0.01}
      />
      <Torus
        uuid="2mWEvRGTwbxIoJCF-3DIW"
        x={3.42}
        y={54.97}
        z={-175.25}
        scaleX={4}
        scaleY={4}
        scaleZ={4}
        castShadow={false}
        receiveShadow={false}
        emissive
        thickness={0.01}
      />
      <Torus
        uuid="_BC2ccgrf9rjD_2ZavHQR"
        x={3.42}
        y={54.97}
        z={-311.72}
        scaleX={4}
        scaleY={4}
        scaleZ={4}
        castShadow={false}
        receiveShadow={false}
        emissive
        thickness={0.01}
      />
      <SpotLight
        uuid="QlrwgE7y3WQ2SycQ4FRN8"
        x={426.68}
        y={481.44}
        z={149.96}
        angle={0.65}
        penumbra={0.4}
        decay={2}
        distance={12.9}
      />
      <Model
        uuid="62gqnZfLuf1XiA-hwWkM9"
        y={49.68}
        width={218.53}
        depth={409.25}
        src="porsche.glb"
        metalnessFactor={1.5}
        envFactor={7}
        reflection
      />
      <Reflector
        uuid="FJXmypZJkJBpO2168LIIy"
        scaleX={100}
        scaleY={100}
        blur={256}
        mirror={0.5}
      />
      <Setup
        defaultLight={false}
        exposure={2}
        bloom
        bloomIntensity={2}
        bloomThreshold={0.49}
      />
    </World>
  )
}

export default App
