import React from "react"
import ICamera from "lingo3d/lib/interface/ICamera"
import IKeyboard from "lingo3d/lib/interface/IKeyboard"
import ILoaded from "lingo3d/lib/interface/ILoaded"
import IModel from "lingo3d/lib/interface/IModel"
import IDummy from "lingo3d/lib/interface/IDummy"
import ISvgMesh from "lingo3d/lib/interface/ISvgMesh"
import IMouse from "lingo3d/lib/interface/IMouse"
import IOrbitCamera from "lingo3d/lib/interface/IOrbitCamera"
import IPrimitive from "lingo3d/lib/interface/IPrimitive"
import ISkybox from "lingo3d/lib/interface/ISkybox"
import ICharacterCamera from "lingo3d/lib/interface/ICharacterCamera"
import IAreaLight from "lingo3d/lib/interface/IAreaLight"
import IPointLight from "lingo3d/lib/interface/IPointLight"
import ISkyLight from "lingo3d/lib/interface/ISkyLight"
import ISpotLight from "lingo3d/lib/interface/ISpotLight"
import IReflector from "lingo3d/lib/interface/IReflector"
import ISprite from "lingo3d/lib/interface/ISprite"
import IAmbientLight from "lingo3d/lib/interface/IAmbientLight"
import IDirectionalLight from "lingo3d/lib/interface/IDirectionalLight"
import ITrigger from "lingo3d/lib/interface/ITrigger"
import ISpawnPoint from "lingo3d/lib/interface/ISpawnPoint"
import IAudio from "lingo3d/lib/interface/IAudio"
import IEnvironment from "lingo3d/lib/interface/IEnvironment"
import IJoystick from "lingo3d/lib/interface/IJoystick"
import IReticle from "lingo3d/lib/interface/IReticle"
import IThirdPersonCamera from "lingo3d/lib/interface/IThirdPersonCamera"
import ISetup from "lingo3d/lib/interface/ISetup"
import IWater from "lingo3d/lib/interface/IWater"

type Children = React.ReactNode



